services:
  web:
    build: .
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - magnetosphere_ru

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - web
      - old
      - ghost
    restart: unless-stopped
    networks:
      - magnetosphere_ru

  old:
    image: php:8.2-apache
    # ports:
    #   - "8889:80"
    volumes:
      - ./old:/var/www/html
      - ./old.conf:/etc/apache2/conf-enabled/old.conf:ro
    restart: unless-stopped
    networks:
      - magnetosphere_ru
  
  ghost:
    image: ghost:5
    restart: always
    depends_on:
      - db
    # ports:
    #   - 8890:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: ${EXTERNAL_GHOST_URL}
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    volumes:
      - ghost:/var/lib/ghost/content
    networks:
      - magnetosphere_ru

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - magnetosphere_ru

volumes:
  ghost:
  db:

networks:
  magnetosphere_ru:
    driver: bridge
